### ISSUE TITLE
Empty DynamicObject with protobuf-net serializer throws exception

### ISSUE THREAD

**Issue by Braidon** [6bee/aqua-core#37]
Hi,

I faced with a serialization problem of a DynamicObject. Empty DynamicObject is incorrectly deserialized by protobuf. I get the last sources to investigate the problem.
To reproduce exception you need to open the "29_RemoteQueryable_UsingProtobufNetSerializationOverTcp" sample, and at first query change
`foreach (var item in await repo.Products.ToArrayAsync().ConfigureAwait(false))`
to
`foreach (var item in await repo.Products.Where(x => x.Id == 0).ToArrayAsync().ConfigureAwait(false))`
Filter can be anything, we need to get an empty result.

As far as I know, problem is at empty array (value of dictionary) of SurrogateDynamicObject. ProtoWriter treat field as a string and deserializer throws an exception. If add check for an empty array and set field to null, everything works, but I prefer to get an empty array as a result.

Why it happens I didn't found yet.

Exception:
System.AggregateException: One or more errors occurred. (Invalid wire-type; this usually means you have over-written a file without truncating or setting the length; see https://stackoverflow.com/q/2152978/23354)
 ---> ProtoBuf.ProtoException: Invalid wire-type; this usually means you have over-written a file without truncating or setting the length; see https://stackoverflow.com/q/2152978/23354
   at ProtoBuf.ProtoReader.SkipField() in c:\Projects\Remote.Linq-main\protobuf\src\protobuf-net\ProtoReader.cs:line 796
   at proto_2(Object , ProtoReader )
   at ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Read(Object value, ProtoReader source)
   at ProtoBuf.Meta.RuntimeTypeModel.Deserialize(Int32 key, Object value, ProtoReader source)
   at ProtoBuf.ProtoReader.ReadTypedObject(Object value, Int32 key, ProtoReader reader, Type type)
   at ProtoBuf.ProtoReader.ReadObject(Object value, Int32 key, ProtoReader reader)
   at proto_244(Object , ProtoReader )
   at ProtoBuf.Serializers.CompiledSerializer.ProtoBuf.Serializers.IProtoSerializer.Read(Object value, ProtoReader source)
   at ProtoBuf.Meta.RuntimeTypeModel.Deserialize(Int32 key, Object value, ProtoReader source)
   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate)
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context)
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type)
   at Common.ProtobufNetFormatter.ReadInternalAsync[T](Stream stream, Type type, CancellationToken cancellation)
   at Common.ProtobufNetFormatter.ReadAsync[T](Stream stream, CancellationToken cancellation)
   at Client.RemoteRepository.<.ctor>b__2_0(Expression expression, CancellationToken cancellation)
   at Remote.Linq.DynamicQuery.AsyncRemoteQueryProvider`1.ExecuteAsync[TResult](Expression expression, CancellationToken cancellation)
   at Remote.Linq.Async.AsyncQueryableExtensions.ExecuteAsync[TResult](IQueryable source, CancellationToken cancellation)
   at Remote.Linq.Async.AsyncQueryableExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken cancellation)
   at Client.AsyncDemo.RunAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at IAsyncDemoExtensions.RunAsyncDemo(IAsyncDemo demo) in c:\Projects\Remote.Linq-main\samples\SharedCode\Client.IAsyncDemo.cs:line 24

**Comment by 6bee** [comment]
The issue should be resolved and can be re-tested using `aqua-core-protobuf-net.5.0.0-beta-003.nupkg` and `Remote.Linq.protobuf-net.7.0.0-beta-002.nupkg` respectively.
